### PR TITLE
Remove exception listeners, rely on Symfony...::logKernelException() to log uncaught exceptions

### LINKED ISSUE #36: Uncaught Exception becomes two occurences in Rollbar app
When using a basic Symfony 4 setup with the setup of the bundle as described in the [Rollbar Symfony docs](https://docs.rollbar.com/docs/symfony), one Exception thrown becomes 2 lines in the occurrences table.

trace.exception.message | custom.channel | custom.datetime | custom.level | custom.payload.body.trace_chain
------------------------ | ---------------- | ----------------- | ------------- | --------------------------
Example msg | app | 1539001010 | error | [{"frames":...
Example msg | request | 1539001009 | critical | (empty)

### Setup

config/bundles.php
```php
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
   /* ... */
   
	// RollbarBundle must be included _after_ MonologBundle
    Rollbar\Symfony\RollbarBundle\RollbarBundle::class => ['prod' => true],
];
```

config/packages/prod/rollbar.yaml
```yaml
rollbar:
  enabled: true
  access_token: '%env(ROLLBAR_TOKEN)%'
  environment: '%env(APP_HOST)%'
```

config/packages/monolog.yaml
```yaml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error # log all errors with status code >= 400
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'noreply@example.org'
            to_email:   '%env(SERVER_ADMIN)%'
            subject:    '%%message%%'
            level:      notice
            formatter:  monolog.formatter.html
            content_type: text/html

```

config/packages/prod/monolog.yaml
```yaml
monolog:
  handlers:
    # This appends `rollbar` to the environment-independent list of handlers
    rollbar:
      type: service
      id: Rollbar\Monolog\Handler\RollbarHandler
```

### PR DESCRIPTION
**Pull request by hngl**
Fixes #36

### CODE REVIEW

**Comment by jessewgibbs** [comment]
@hngl thanks for the contribution!

@ArturMoczulski can you review this when you get a chance?

**Comment by hngl** [comment]
Tests pass, yet `phpunit` exits non-zero because of [issue 2775](https://github.com/sebastianbergmann/phpunit/issues/2775)

**Comment by ArturMoczulski** [comment]
I verified the broken build is not a result of the PR and can happen in the `master` branch as well, so I'm merging the PR in. The `phpunit` exiting with a non-zero status will be resolved in a separate issue.

**Comment by hngl** [comment]
@ArturMoczulski Thanks for reviewing. 👍 Could you please publish the result to [packagist](https://packagist.org/packages/rollbar/rollbar-php-symfony-bundle)?

**Comment by hngl** [comment]
@jessewgibbs Could you please publish the new master to packagist?

**Comment by ArturMoczulski** [comment]
`v3.1.0` was published to packagist a while back. @hngl can you verify that you can pull that version from packagist?

**Pull request merged**
