### PR TITLE
Possibility to use service as person_fn rather than a static function

### LINKED ISSUE #52: Possibility to use service as person_fn rather than a static function
We can only use a static function for `person_fn` which is not really useful since most of the time we'd want to access some dependencies from inside the function and thus use a service instead of a static.

In older versions of Rollbar, we were able to add `person` data from inside a `monolog.processor` tagged service. Like that:

```php
class RollbarContextProcessor
{
    /** @var TokenStorageInterface */
    protected $tokenStorageInterface;
    
    public function __construct(TokenStorageInterface $tokenStorageInterface)
    {
        $this->tokenStorageInterface = $tokenStorageInterface;
    }    

    public function processRecord(array $record): array
    {
        $record = $this->recordUser($record);
    }

    private function recordUser(array $record): array
    {
        if (!\is_object($this->tokenStorageInterface->getToken())) {
            return $record;
        }

        /** @var User $user */
        $user = $this->tokenStorageInterface->getToken()->getUser();

        if ($user instanceof User) {
            $record['context']['payload']['person'] = [
                'id'         => $user->getId(),
                'username'   => $user->getUsername(),
                'facebookId' => $user->getFacebookId(),
                'roles'      => implode('|', $user->getRoles())
            ];
        }

        return $record;
    }
}
```

But as of now, Rollbar doesn't consider this as being `person` data (like before) as it is added in `body.extra` variables.

### PR DESCRIPTION
**Pull request by zinkovskiy**
## Description of the change

This PR allow to use service as `person_fn`

I created PersonProvider service that is used by default

To use custom person provider you need to define your own service with alias `rollbar.person-provider` in services.yml of your application, for example:
```yml
  rollbar.person-provider:
    class: App\Service\Rollbar\Provider\PersonProvider
```

No need to define `person_fn` option (thx to DI), the service will be used automatically, but if `person_fn` is defined, then it will be used

Logic of obtaining user info is not changed.

I've also discovered, that `security.token_storage` and `serializer` are private and cannot be obtained from container, so I passed it to `Rollbar\Symfony\RollbarBundle\Factories\RollbarHandlerFactory` constructor

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)

## Related issues

- Fix #52 

### Development

- [ ] All tests related to the changed code pass in development

### Code review

I tested these changes on symfony 5.4 and symfony 6.4, it works well

@danielmorell could you please take a look on it?

### CODE REVIEW

**Comment by zdavis-rollbar** [comment]
@zinkovskiy, we are looking for a maintainer or owner of the repo.  Would you like to participate?

**Comment by zinkovskiy** [comment]
> @zinkovskiy, we are looking for a maintainer or owner of the repo. Would you like to participate?

Hi @zdavis-rollbar yes, I'm ready to maintain. contact me anytime when you have time, we are interested in keeping the project up to date

**Comment by waltjones** [comment]
@zinkovskiy Thank you for the PR. Please add tests for the new functionality, and run tests locally to ensure CI will pass.

**Comment by zinkovskiy** [comment]
> @zinkovskiy Thank you for the PR. Please add tests for the new functionality, and run tests locally to ensure CI will pass.

Hi @waltjones, yes, I missed it. Now it's added 
Hope it helps to accept changes :slightly_smiling_face:

**Review by danielmorell — APPROVED** [review]
Hey Anton, thank you for your work on this and your patience in getting this reviewed!

I appreicate how customizable and extensible you have made this. Great work!

**Pull request closed without merging**
