### PR TITLE
Fix for Issue #49 - TreeBuilder Deprecation.

### PR DESCRIPTION
**Pull request by ellisgl**
Issue #49

### CODE REVIEW

**Comment by ellisgl** [comment]
@Yozhef @ArturMoczulski Any chance of having this looked at / merged?

**Comment by Yozhef** [comment]
@ellisgl Sorry, I can not tell, I'm a simple developer and also waiting to merge my decision.

**Comment by ellisgl** [comment]
@Yozhef ah, I thought you were merge person. Sorry about that.

**Comment by ArturMoczulski** [comment]
Merged into `master`. I will get it released by tomorrow

**Pull request merged**
