### PR TITLE
Support PHP 8

### LINKED ISSUE #1: Improve documentation in README.md

### PR DESCRIPTION
**Pull request by janicekt**
## Description of the change

> adds PHP 8 support and updates the [Rollbar-php](https://github.com/rollbar/rollbar-php/tree/v3.0.0) package to a php8 supported version. Remove PHP 7 support because it is no longer supported in new version [Rollbar-php](https://github.com/rollbar/rollbar-php/tree/v3.0.0)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance
- [ ] New release

## Related issues

> Shortcut stories and GitHub issues (delete irrelevant)

- Fix [SC-]
- Fix #1

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] "Ready for review" label attached to the PR and reviewers assigned
- [ ] Issue from task tracker has a link to this pull request
- [ ] Changes have been reviewed by at least one other engineer

### CODE REVIEW

**Comment by janicekt** [comment]
this fork i have thrown it on my private project and it works fine ..

**Comment by art-cg** [comment]
Thanks for the PR. I am not sure if it works with symfony 5.0. Hard to tell without Github Actions (maybe you can run your the tests local with  composer install --prefer-lowest). 

And we need another PR to add more php versions in Travis (merged upfront) https://github.com/rollbar/rollbar-php-symfony-bundle/blob/master/.travis.yml
Or even better GithubActions tests

**Comment by art-cg** [comment]
@janicekt What do you think about my [PR ](https://github.com/rollbar/rollbar-php-symfony-bundle/pull/73) based on this one?

**Comment by janicekt** [comment]
> Thanks for the PR. I am not sure if it works with symfony 5.0. Hard to tell without Github Actions (maybe you can run your the tests local with composer install --prefer-lowest).
> 
> And we need another PR to add more php versions in Travis (merged upfront) https://github.com/rollbar/rollbar-php-symfony-bundle/blob/master/.travis.yml Or even better GithubActions tests

in PHP 8.1 with lowest deps are not tests works because there are PHP deprecations in external deps. That's only OK locally with Symfony 5.4 and newer. Its would be nice to have travis 
Snímek obrazovky 2022-01-06 v 13 52 32
Snímek obrazovky 2022-01-06 v 13 54 30

**Comment by janicekt** [comment]
> Thanks for the PR. I am not sure if it works with symfony 5.0. Hard to tell without Github Actions (maybe you can run your the tests local with composer install --prefer-lowest).
> 
> And we need another PR to add more php versions in Travis (merged upfront) https://github.com/rollbar/rollbar-php-symfony-bundle/blob/master/.travis.yml Or even better GithubActions tests

but I already run it on my project with php 8.1 and Symfony 5.4

> Thanks for the PR. I am not sure if it works with symfony 5.0. Hard to tell without Github Actions (maybe you can run your the tests local with composer install --prefer-lowest).
> 
> And we need another PR to add more php versions in Travis (merged upfront) https://github.com/rollbar/rollbar-php-symfony-bundle/blob/master/.travis.yml Or even better GithubActions tests

**Comment by janicekt** [comment]
> Thanks for the PR. I am not sure if it works with symfony 5.0. Hard to tell without Github Actions (maybe you can run your the tests local with composer install --prefer-lowest).
> 
> And we need another PR to add more php versions in Travis (merged upfront) https://github.com/rollbar/rollbar-php-symfony-bundle/blob/master/.travis.yml Or even better GithubActions tests

thanks for the comment. Should I incorporate a .travis configuration update?

**Comment by art-cg** [comment]
Travis is not running on PR right know (but i guess maintainer has more infos about the usage). I hope i find the time to port it to GitHub Actions

**Comment by danielmorell** [comment]
Hi @janicekt, thank you for your work on this! We have moved development for PHP 8 to the [`next/5.x/main`](https://github.com/rollbar/rollbar-php-symfony-bundle/tree/next/5.x/main) branch. We are also planning on using GitHub Actions for our CI. We have merged both #73 and #74 into `next/5.x/main`.

If there is anything you think is important that was not included already, you could merge `next/5.x/main` into your branch and update this PR.

**Comment by janicekt** [comment]
on my version I have been working on symfony 5.4 with php8.1 for some time and without any problems .. I'm going to test the transition to 5.0-RC1 version

**Comment by danielmorell** [comment]
Today we released the stable v5.0.0. I am going to go ahead and close this PR. @janicekt thank you for your work on this. If, there is anything in here that we are missing in v5, please let's talk about it and figure out a way to move it forward.

**Pull request closed without merging**
